// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXhr7IwsKG3pOLw7g7oADH3ZPtqCprmBg',
    appId: '1:27144937910:web:afb352461c29aad0d2e117',
    messagingSenderId: '27144937910',
    projectId: 'bodaapp-23c75',
    authDomain: 'bodaapp-23c75.firebaseapp.com',
    storageBucket: 'bodaapp-23c75.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFslePYpC2jJ5VC5DY6NPqnJefoprCs-M',
    appId: '1:27144937910:android:ff33e9c6f2609a3ed2e117',
    messagingSenderId: '27144937910',
    projectId: 'bodaapp-23c75',
    storageBucket: 'bodaapp-23c75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzbawjTKxFaKK9ShLRjhhcEmFN9vY5Goo',
    appId: '1:27144937910:ios:c4726c25bacca87dd2e117',
    messagingSenderId: '27144937910',
    projectId: 'bodaapp-23c75',
    storageBucket: 'bodaapp-23c75.appspot.com',
    iosBundleId: 'com.example.bodaApp',
  );
}
