// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuKnns8ZuvF7ugZ-VTythAzf6wg7HkYGM',
    appId: '1:990360528512:web:35292989175e32bfdda865',
    messagingSenderId: '990360528512',
    projectId: 'boda-7b2fc',
    authDomain: 'boda-7b2fc.firebaseapp.com',
    storageBucket: 'boda-7b2fc.appspot.com',
    measurementId: 'G-J9LFLXP9V4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTtBlGguM-e5GOXdiaxoE2lb9juXV4Gqk',
    appId: '1:990360528512:android:387857bc366c1884dda865',
    messagingSenderId: '990360528512',
    projectId: 'boda-7b2fc',
    storageBucket: 'boda-7b2fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtvY7iSqMJOGAZlfdhIzkxVweYhj_E3ZQ',
    appId: '1:990360528512:ios:a9b105cd711c45a3dda865',
    messagingSenderId: '990360528512',
    projectId: 'boda-7b2fc',
    storageBucket: 'boda-7b2fc.appspot.com',
    iosBundleId: 'com.example.boda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtvY7iSqMJOGAZlfdhIzkxVweYhj_E3ZQ',
    appId: '1:990360528512:ios:a9b105cd711c45a3dda865',
    messagingSenderId: '990360528512',
    projectId: 'boda-7b2fc',
    storageBucket: 'boda-7b2fc.appspot.com',
    iosBundleId: 'com.example.boda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuKnns8ZuvF7ugZ-VTythAzf6wg7HkYGM',
    appId: '1:990360528512:web:07cfb07851db65dbdda865',
    messagingSenderId: '990360528512',
    projectId: 'boda-7b2fc',
    authDomain: 'boda-7b2fc.firebaseapp.com',
    storageBucket: 'boda-7b2fc.appspot.com',
    measurementId: 'G-G589ZWR01M',
  );
}
